# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_suprema = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_suprema.setGeometry(QtCore.QRect(10, 10, 621, 291))
        self.groupBox_suprema.setObjectName("groupBox_suprema")
        self.pushButton_pc2fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_pc2fv_suprema.setGeometry(QtCore.QRect(20, 20, 105, 35))
        self.pushButton_pc2fv_suprema.setObjectName("pushButton_pc2fv_suprema")
        self.pushButton_pc3fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_pc3fv_suprema.setGeometry(QtCore.QRect(20, 60, 105, 35))
        self.pushButton_pc3fv_suprema.setObjectName("pushButton_pc3fv_suprema")
        self.pushButton_pc4fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_pc4fv_suprema.setGeometry(QtCore.QRect(20, 100, 105, 35))
        self.pushButton_pc4fv_suprema.setObjectName("pushButton_pc4fv_suprema")
        self.pushButton_pc4fvma_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_pc4fvma_suprema.setGeometry(QtCore.QRect(20, 140, 105, 35))
        self.pushButton_pc4fvma_suprema.setObjectName("pushButton_pc4fvma_suprema")
        self.pushButton_pc6fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_pc6fv_suprema.setGeometry(QtCore.QRect(20, 180, 105, 35))
        self.pushButton_pc6fv_suprema.setObjectName("pushButton_pc6fv_suprema")
        self.pushButton_pc8fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_pc8fv_suprema.setGeometry(QtCore.QRect(20, 220, 105, 35))
        self.pushButton_pc8fv_suprema.setObjectName("pushButton_pc8fv_suprema")
        self.pushButton_jc2fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_jc2fv_suprema.setGeometry(QtCore.QRect(140, 20, 105, 35))
        self.pushButton_jc2fv_suprema.setObjectName("pushButton_jc2fv_suprema")
        self.pushButton_jc3fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_jc3fv_suprema.setGeometry(QtCore.QRect(140, 60, 105, 35))
        self.pushButton_jc3fv_suprema.setObjectName("pushButton_jc3fv_suprema")
        self.pushButton_jc4fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_jc4fv_suprema.setGeometry(QtCore.QRect(140, 100, 105, 35))
        self.pushButton_jc4fv_suprema.setObjectName("pushButton_jc4fv_suprema")
        self.pushButton_jc4fvma_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_jc4fvma_suprema.setGeometry(QtCore.QRect(140, 140, 105, 35))
        self.pushButton_jc4fvma_suprema.setObjectName("pushButton_jc4fvma_suprema")
        self.pushButton_jc6fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_jc6fv_suprema.setGeometry(QtCore.QRect(140, 180, 105, 35))
        self.pushButton_jc6fv_suprema.setObjectName("pushButton_jc6fv_suprema")
        self.pushButton_jc8fv_suprema = QtWidgets.QPushButton(self.groupBox_suprema)
        self.pushButton_jc8fv_suprema.setGeometry(QtCore.QRect(140, 220, 105, 35))
        self.pushButton_jc8fv_suprema.setObjectName("pushButton_jc8fv_suprema")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_suprema.setTitle(_translate("MainWindow", "Linha Suprema"))
        self.pushButton_pc2fv_suprema.setText(_translate("MainWindow", "Porta correr\n"
" 2 folhas vidro"))
        self.pushButton_pc3fv_suprema.setText(_translate("MainWindow", "Porta correr\n"
"3 folhas vidro"))
        self.pushButton_pc4fv_suprema.setText(_translate("MainWindow", "Porta correr\n"
" 4 folhas vidro"))
        self.pushButton_pc4fvma_suprema.setText(_translate("MainWindow", "Porta correr \n"
"4 folhas MA vidro"))
        self.pushButton_pc6fv_suprema.setText(_translate("MainWindow", "Porta correr \n"
"6 folhas vidro"))
        self.pushButton_pc8fv_suprema.setText(_translate("MainWindow", "Porta correr \n"
"8 folhas vidro"))
        self.pushButton_jc2fv_suprema.setText(_translate("MainWindow", "Janela correr\n"
" 2 folhas vidro"))
        self.pushButton_jc3fv_suprema.setText(_translate("MainWindow", "Janela correr\n"
"3 folhas vidro"))
        self.pushButton_jc4fv_suprema.setText(_translate("MainWindow", "Janela correr\n"
" 4 folhas vidro"))
        self.pushButton_jc4fvma_suprema.setText(_translate("MainWindow", "Janela correr \n"
"4 folhas MA vidro"))
        self.pushButton_jc6fv_suprema.setText(_translate("MainWindow", "Janela correr \n"
"6 folhas vidro"))
        self.pushButton_jc8fv_suprema.setText(_translate("MainWindow", "Janela correr \n"
"8 folhas vidro"))



