# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relatorio.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_relatorio(object):


    def setupUi(self, relatorio):
        relatorio.setObjectName("relatorio")
        relatorio.resize(600, 470)
        relatorio.setMinimumSize(QtCore.QSize(600, 470))
        self.centralwidget = QtWidgets.QWidget(relatorio)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_tabela = QtWidgets.QFrame(self.centralwidget)
        self.frame_tabela.setGeometry(QtCore.QRect(0, 0, 598, 371))
        self.frame_tabela.setStyleSheet("\n"
"")
        self.frame_tabela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabela.setObjectName("frame_tabela")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_tabela)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_tabela = QtWidgets.QTableWidget(self.frame_tabela)
        self.tableWidget_tabela.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_tabela.setAutoScrollMargin(16)
        self.tableWidget_tabela.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_tabela.setAlternatingRowColors(True)
        self.tableWidget_tabela.setObjectName("tableWidget_tabela")
        self.tableWidget_tabela.setColumnCount(3)
        self.tableWidget_tabela.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tabela.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tabela.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tabela.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tabela.setHorizontalHeaderItem(2, item)
        self.tableWidget_tabela.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_tabela.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_tabela.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_tabela.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_tabela.verticalHeader().setVisible(False)
        self.tableWidget_tabela.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_tabela.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_tabela.verticalHeader().setHighlightSections(True)
        self.tableWidget_tabela.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.tableWidget_tabela)
        self.frame_botoes = QtWidgets.QFrame(self.centralwidget)
        self.frame_botoes.setGeometry(QtCore.QRect(130, 390, 340, 43))
        self.frame_botoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botoes.setObjectName("frame_botoes")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_botoes)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_salvar = QtWidgets.QPushButton(self.frame_botoes)
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        self.horizontalLayout_2.addWidget(self.pushButton_salvar)
        self.pushButton = QtWidgets.QPushButton(self.frame_botoes)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_fechar = QtWidgets.QPushButton(self.frame_botoes)
        self.pushButton_fechar.setObjectName("pushButton_fechar")
        self.horizontalLayout_2.addWidget(self.pushButton_fechar)
        relatorio.setCentralWidget(self.centralwidget)

        self.retranslateUi(relatorio)
        QtCore.QMetaObject.connectSlotsByName(relatorio)

    def retranslateUi(self, relatorio):
        _translate = QtCore.QCoreApplication.translate
        relatorio.setWindowTitle(_translate("relatorio", "Relatório de Materiais"))
        item = self.tableWidget_tabela.verticalHeaderItem(0)
        item.setText(_translate("relatorio", "linha 1"))
        item = self.tableWidget_tabela.verticalHeaderItem(1)
        item.setText(_translate("relatorio", "linha 2"))
        item = self.tableWidget_tabela.horizontalHeaderItem(0)
        item.setText(_translate("relatorio", "codigo"))
        item = self.tableWidget_tabela.horizontalHeaderItem(1)
        item.setText(_translate("relatorio", "quatidade"))
        item = self.tableWidget_tabela.horizontalHeaderItem(2)
        item.setText(_translate("relatorio", "descrição"))
        self.pushButton_salvar.setText(_translate("relatorio", "Salvar"))
        self.pushButton.setText(_translate("relatorio", "Limpar"))
        self.pushButton_fechar.setText(_translate("relatorio", "Fechar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    relatorio = QtWidgets.QMainWindow()
    ui = Ui_relatorio()
    ui.setupUi(relatorio)
    relatorio.show()
    sys.exit(app.exec_())
